---
- name: Apply patches to endpoints
  hosts: "{{ target | default('all') }}"
  become: true
  tasks:
    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Apply security updates
      package:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
